### ISSUE TITLE
Certificate Based Authentication, Bad Request

### ISSUE THREAD

**Issue by autsakorn** [SaxoBank/openapi-samples-js#16]
I followed your instructions. https://github.com/SaxoBank/openapi-samples-js/tree/master/authentication/oauth2-certificate-flow/example_nodejs

I got "Bad Request". and I try to change Cert and config more, but I still got "Bad Request"
Do do have any idea for help me?

**Comment by basgroot** [comment]
Hi @autsakorn ,

Thanks for your interest in the SaxoBank OpenApi and its samples.
The CBA flow is only available for licensed third parties. I've added a note to the samples to make this more clear.

I can imagine this is not the answer you were looking for, but still answers your question.

Regards,
Bas

**Comment by autsakorn** [comment]
I have licensed and I download a Certificate from SaxoTraderGO.
It is good if you can help to make this more clear.

Best Regards

**Comment by basgroot** [comment]
Hi good morning,

The CBA authentication is only available for selected partners on SaxoBank, upon request.
I can recommend using the Code or PKCE flow for getting an access token.

Regards,
Bas

**Comment by autsakorn** [comment]
@basgroot 

I understood, I work for selected partners on SaxoBank.

I have User ID for download Certificate .p12. and used App Key on "Application Management".
Can you help to make this more clear?

Best Regards,

**Comment by basgroot** [comment]
Hi @autsakorn ,

OK, I understand. Can you send the following details to openapisupport@saxobank.com along with a reference to this conversation. Then we'll help you solving this issue:

1. Name of the partner you are working for
2. SIM App Key
3. SIM App Redirect URL
4. SIM ClientId
5. Date and time of receiving the 400.

Thanks,
Bas
